apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sjkhr2hz3-python 
  janus-idp.io/tekton: sjkhr2hz3-python
  backstage.io/kubernetes-id: sjkhr2hz3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sjkhr2hz3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml